# Generated by Django 2.2.4 on 2019-08-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('email', models.TextField(null=True)),
                ('issue_summary', models.TextField(null=True)),
                ('extra_details', models.TextField(null=True)),
            ],
        ),
    ]
